### ISSUE TITLE
PHP8 support

### ISSUE THREAD

**Issue by affektde** [RichardStyles/eloquent-aes#2]
My question is, will this package also support PHP 8 in the future?

**Comment by RichardStyles** [comment]
There is an intention to support PHP 8 of course. Seeing as [Laravel 8 is now ready for PHP 8](https://blog.laravel.com/laravel-php-8-support) this should be simple enough, I'm more than happy to look at a PR if anyone gets to it before I do.

**Comment by hooman-mirghasemi** [comment]
please change your compose.json for installing in php 8

**Comment by RichardStyles** [comment]
The PR to support PHP 8.0 since ([v2.0.0](https://github.com/RichardStyles/eloquent-aes/releases/tag/v2.0.0)) (and Laravel 9 - [v2.1.0](https://github.com/RichardStyles/eloquent-aes/releases/tag/v2.1.0)) has been merged in
