### ISSUE TITLE
Can search with encrypted data?

### ISSUE THREAD

**Issue by hooman-mirghasemi** [RichardStyles/eloquent-aes#5]
can  i set user name as encrypted.
then run this:

User::where('name','testname')->get();

Is top code work correctly  with this package?

**Comment by thyseus** [comment]
No, you can not search encrypted columns.

**Comment by RichardStyles** [comment]
You should only encrypt data that you wouldn't search against. 
If you _need_ to encrypt everything then I'd advise speaking to a security professional.

**Comment by RichardStyles** [comment]
@hooman-mirghasemi  Found this https://ciphersweet.paragonie.com/  which has a spatie package https://packagist.org/packages/spatie/laravel-ciphersweet which might suit your use case.
